[{
  "/acl/menus": {
    "code": 0,
    "msg": "OK",
    "result": null,
    "menuId": "-1",
    "menuParentId": null,
    "menuName": "root",
    "menuTitle": "root",
    "menuUrl": null,
    "permissionName": null,
    "subMenus": [{
      "code": 0,
      "msg": "OK",
      "result": null,
      "menuId": "100025925",
      "menuParentId": "-1",
      "menuName": "root_index",
      "menuTitle": "首页",
      "menuUrl": "/index",
      "permissionName": null,
      "subMenus": [],
      "sort": "1000",
      "leaf": true,
      "success": true
    }, {
      "code": 0,
      "msg": "OK",
      "result": null,
      "menuId": "100025924",
      "menuParentId": "-1",
      "menuName": "root_company",
      "menuTitle": "竞争厂商",
      "menuUrl": "",
      "permissionName": "sandtable_company",
      "subMenus": [{
        "code": 0,
        "msg": "OK",
        "result": null,
        "menuId": "100025926",
        "menuParentId": "100025924",
        "menuName": "dir_company_aliyun",
        "menuTitle": "阿里云",
        "menuUrl": "",
        "permissionName": "sandtable_company",
        "subMenus": [{
          "code": 0,
          "msg": "OK",
          "result": null,
          "menuId": "100025927",
          "menuParentId": "100025926",
          "menuName": "page_company_aliyun_productoverview",
          "menuTitle": "产品大图",
          "menuUrl": "/static/company/aliyun/product_overview.html",
          "permissionName": "sandtable_company",
          "subMenus": [],
          "sort": "2110",
          "leaf": true,
          "success": true
        }],
        "sort": "2100",
        "leaf": false,
        "success": true
      }],
      "sort": "2000",
      "leaf": false,
      "success": true
    }, {
      "code": 0,
      "msg": "OK",
      "result": null,
      "menuId": "100025928",
      "menuParentId": "-1",
      "menuName": "root_market",
      "menuTitle": "市场洞悉",
      "menuUrl": "",
      "permissionName": "sandtable_market",
      "subMenus": [{
        "code": 0,
        "msg": "OK",
        "result": null,
        "menuId": "100025929",
        "menuParentId": "100025928",
        "menuName": "page_market_region",
        "menuTitle": "全球布局",
        "menuUrl": "/static/market/region.html",
        "permissionName": "sandtable_market_region",
        "subMenus": [],
        "sort": "3100",
        "leaf": true,
        "success": true
      }],
      "sort": "3000",
      "leaf": false,
      "success": true
    }, {
      "code": 0,
      "msg": "OK",
      "result": null,
      "menuId": "100025930",
      "menuParentId": "-1",
      "menuName": "root_research",
      "menuTitle": "深度分析",
      "menuUrl": "",
      "permissionName": "sandtable_research",
      "subMenus": [{
        "code": 0,
        "msg": "OK",
        "result": null,
        "menuId": "100025931",
        "menuParentId": "100025930",
        "menuName": "dir_research_conference",
        "menuTitle": "会议解读",
        "menuUrl": "/articles",
        "permissionName": "sandtable_research",
        "subMenus": [],
        "sort": "4100",
        "leaf": true,
        "success": true
      }],
      "sort": "4000",
      "leaf": false,
      "success": true
    }, {
      "code": 0,
      "msg": "OK",
      "result": null,
      "menuId": "100025932",
      "menuParentId": "-1",
      "menuName": "root_news",
      "menuTitle": "竞争动态",
      "menuUrl": "",
      "permissionName": "sandtable_news",
      "subMenus": [{
        "code": 0,
        "msg": "OK",
        "result": null,
        "menuId": "100025933",
        "menuParentId": "100025932",
        "menuName": "dir_news_daily",
        "menuTitle": "日报",
        "menuUrl": "/articles/daily/",
        "permissionName": "sandtable_news",
        "subMenus": [],
        "sort": "5100",
        "leaf": true,
        "success": true
      }],
      "sort": "5000",
      "leaf": false,
      "success": true
    }],
    "sort": null,
    "leaf": false,
    "success": true
  }
}, {
  "/article/130": {
    "id": 130,
    "author": null,
    "title": "daily report for test 2016-08-08T11:51:37.754+08:00",
    "summary": null,
    "content": "��?�C��?? > ?�졮??�� > IT?????? > ????�C?\n��?��???��??��???���????????��?????����????����???��??��?��??10???????��?\n????????? ??��??��??��??? | 2015-06-01 16:25:23| ???���㡭??????��??\n????????��???\n?���?���??��??��?�졮??�㨨?? 6???1?��??????????��?��???��??��??��??????����????���??��??????????�C?��?????��?��?��??��?????�C???��??��??????��???��??????��?��????��???��?????????����????����???��???��????????�訨????��?????��?��?��????��10???????��??��?\n?���?���CEO��??????????����?�㨨�㡭����?��???????����????��???��?��???��?????��????��????????????????��???????��???????????60%��??70%?��?\n?���?��㨨?��???��?????��???��???��??��?����???��????��?��??????????????��???????GPU��???��??��?��???��???????����?��??????��??�C???�먨????????????��??????��?��???�먨???��?��??��???????????????��????��??????��?\n?���?��㨦????????��?��?��??????����????��?????????��???��?��???????��????????��??��?��쨦?????????????����?��??��???????��???�C��???????????��?��???��?????GPU?????��????��???��?����??????????????��?����????��?��?????Siri?��???????��??��???��???��???��??????��?(???��??)\n",
    "category": "daily",
    "status": 1,
    "tags": "",
    "is_favorite": false,
    "is_thumbed": false,
    "num_thumbed": 0,
    "num_favorite": 0,
    "num_comment": 2,
    "num_read": null,
    "attachments": [],
    "comments": {
      "count": 2,
      "data": [{
        "articleId": null,
        "status": null,
        "id": 11,
        "content": "ordinary comment",
        "author": {
          "id": 1,
          "lastName": "单元测试",
          "empId": "999999",
          "nickNameCn": "单测",
          "img": "https://work.alibaba-inc.com/photo/1.jpg"
        }
      }]
    },
    "cover": "http://jingpin-sandtable-test.oss-cn-hangzhou-zmf.aliyuncs.com/cover/130",
    "source": "http://sample-source.com",
    "create": "2017-01-01 00:00:00",
    "modified": "2016-08-08 11:51:37",
    "emphasizedComment": {
      "articleId": null,
      "status": null,
      "id": 12,
      "content": "emphasized comment",
      "author": {"id": 1, "lastName": "单元测试", "empId": "999999", "nickNameCn": "单测", "img": null}
    },
    "recommend": true
  }
}]